development:
  secret_key_base: 'c7051562560d00e087ef47c231d7bb5e9709f0cbbf62eb84fec5a522a4c7049e0464d4c4d3f7277be51f84946e65fa9f54662fc243049851dd9c42aa041ca1c9'
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>